### ISSUE TITLE
Parse Excel Sheets

### ISSUE THREAD

**Issue by GalenChang** [visualizing-your-future/visualizing-your-future#24]
Do all work for this task in a branch called issue-24

Sub-issue for branch 11.

Write functions that will parse Excel sheets.  Use the sheets provided by the client in Laulima.

**Comment by hoangtng** [comment]
<img width="1792" alt="Excel" src="https://github.com/user-attachments/assets/53e11d71-e926-4154-91c7-0bd13feab8e0">
Created a function that parses Excel sheet files. It allows users to import Excel sheets and parse them to JSON. Then, it loads the data back into a table for the user. The user can select a specific sheet in the Excel file to load. But the UI is not great yet because the content structure in the Excel file is messy and confusing. We need to discuss more about the Excel sheets further and define each part for data collection.
